### ISSUE TITLE
no section error

### ISSUE THREAD

**Issue by varunsriram-0824** [bootphon/prosolia#1]
prosolia 0a7c2a8d_nohash_0.wav -c ./prosolia.cfg -o some_features.mat

i seem to be getting a nosection error for this any way to fix this

this is the error message i get-
backports.configparser.NoSectionError: No section: 'filterbank'

**Comment by mmmaat** [comment]
Hello, this is an issue with your configuration file, could you paste the content of your `./prosolia.cfg` please?
